#!/usr/bin/env bash
# Bootstraps this dashboard on a fresh Debian/Ubuntu VPS.
#
#   curl -fsSL https://raw.githubusercontent.com/Yuefan/e-mart/main/scripts/deploy-vps.sh -o deploy.sh
#   less deploy.sh          # read it before running anything as root
#   sudo bash deploy.sh
#
# Safe to re-run: it never regenerates secrets that already exist, because
# rotating ENCRYPTION_KEY would orphan every stored third-party credential.

set -euo pipefail

APP_DIR="${APP_DIR:-/srv/e-mart}"
REPO="${REPO:-https://github.com/Yuefan/e-mart.git}"
ENV_FILE="$APP_DIR/.env.production"

say()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[33m    %s\033[0m\n' "$*"; }
die()  { printf '\n\033[31m!!  %s\033[0m\n' "$*" >&2; exit 1; }

# ---------- preflight ----------

[ "$(id -u)" -eq 0 ] || die "Run with sudo — this installs packages and writes to $APP_DIR."

command -v apt-get >/dev/null || die "This script assumes Debian/Ubuntu. On another distro, follow docs/deployment.md by hand."

say "Checking ports 80 and 443"
for port in 80 443; do
  if ss -ltn "sport = :$port" 2>/dev/null | grep -q LISTEN; then
    die "Port $port is already in use. Caddy needs both to issue a certificate. Stop the other service (often apache2 or nginx) first."
  fi
done

# ---------- docker ----------

if ! command -v docker >/dev/null; then
  say "Installing Docker"
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg 2>/dev/null \
    || curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
       | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  distro=$(. /etc/os-release && echo "$ID")
  codename=$(. /etc/os-release && echo "${VERSION_CODENAME:-$UBUNTU_CODENAME}")
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$distro $codename stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
else
  say "Docker already installed ($(docker --version))"
fi

docker compose version >/dev/null 2>&1 || die "The docker compose plugin is missing. Install docker-compose-plugin."

# ---------- source ----------

if [ -d "$APP_DIR/.git" ]; then
  say "Updating $APP_DIR"
  git -C "$APP_DIR" pull --ff-only
else
  say "Cloning into $APP_DIR"
  command -v git >/dev/null || apt-get install -y -qq git
  mkdir -p "$(dirname "$APP_DIR")"
  git clone --depth 50 "$REPO" "$APP_DIR"
fi
cd "$APP_DIR"

# ---------- configuration ----------

# Written once. Re-running reads the existing values instead of replacing them:
# a new ENCRYPTION_KEY would leave every stored token undecryptable.
if [ -f "$ENV_FILE" ]; then
  say "Reusing existing $ENV_FILE"
  warn "Delete it and re-run if you want to start over — you will have to re-authorize Google."
else
  say "Creating $ENV_FILE"

  gen() { openssl rand -hex 32; }
  command -v openssl >/dev/null || apt-get install -y -qq openssl

  read -rp "    Domain pointing at this server (e.g. dash.example.com): " APP_DOMAIN
  [ -n "$APP_DOMAIN" ] || die "A domain is required — Caddy issues the TLS certificate for it."

  echo
  echo "    Google OAuth (see docs/google-oauth-setup.md). Leave blank to fill in later;"
  echo "    the app starts either way and tells you what is missing."
  read -rp "    GOOGLE_CLIENT_ID: " GOOGLE_CLIENT_ID
  read -rsp "    GOOGLE_CLIENT_SECRET (hidden): " GOOGLE_CLIENT_SECRET; echo

  echo
  echo "    AI gateway (see docs/ai-gateway-setup.md). Blank is fine — audits still"
  echo "    run, you just lose prioritisation and content generation."
  read -rp "    AI_BASE_URL: " AI_BASE_URL
  read -rsp "    AI_API_KEY (hidden): " AI_API_KEY; echo

  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy-vps.sh on $(date -u +%FT%TZ)
# Keep a copy of ENCRYPTION_KEY somewhere safe and separate from the database
# backup: without it every stored third-party token is unreadable.

APP_DOMAIN="$APP_DOMAIN"
APP_URL="https://$APP_DOMAIN"

POSTGRES_USER="app"
POSTGRES_PASSWORD="$(gen)"
POSTGRES_DB="marketing"

ENCRYPTION_KEY="$(gen)"
SESSION_SECRET="$(gen)"

GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID"
GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET"

AI_BASE_URL="$AI_BASE_URL"
AI_API_KEY="$AI_API_KEY"
AI_MODEL_ANALYSIS="claude-opus-5"
AI_MODEL_FAST="claude-haiku-4-5"
AI_EFFORT="medium"
AI_MAX_MONTHLY_USD="50"
EOF
  chmod 600 "$ENV_FILE"
fi

APP_DOMAIN=$(grep -E '^APP_DOMAIN=' "$ENV_FILE" | cut -d'"' -f2)

# ---------- DNS sanity ----------

say "Checking DNS for $APP_DOMAIN"
resolved=$(getent hosts "$APP_DOMAIN" 2>/dev/null | awk '{print $1}' | head -1 || true)
public=$(curl -fsS --max-time 10 https://api.ipify.org 2>/dev/null || echo "")
if [ -z "$resolved" ]; then
  warn "$APP_DOMAIN does not resolve yet. Caddy will keep retrying; add the A record when you can."
elif [ -n "$public" ] && [ "$resolved" != "$public" ]; then
  warn "$APP_DOMAIN resolves to $resolved but this server is $public."
  warn "Certificate issuance will fail until the A record points here."
else
  echo "    $APP_DOMAIN -> $resolved"
fi

# ---------- build and start ----------

say "Building and starting (first build takes a few minutes)"
docker compose --env-file "$ENV_FILE" up -d --build

say "Waiting for migrations"
if ! docker compose --env-file "$ENV_FILE" logs migrate 2>&1 | tail -20; then
  warn "Could not read migrate logs."
fi

say "Service status"
docker compose --env-file "$ENV_FILE" ps

# ---------- verify ----------

say "Checking the app answers locally"
for _ in $(seq 1 30); do
  if curl -fsS --max-time 5 http://127.0.0.1:3000/login >/dev/null 2>&1; then
    echo "    web is serving on 127.0.0.1:3000"
    break
  fi
  sleep 2
done

say "Outbound reachability (Google)"
curl -fsS --max-time 30 http://127.0.0.1:3000/api/diagnostics/google 2>/dev/null || \
  warn "Could not read the diagnostics endpoint yet."

cat <<EOF

$(printf '\033[1m')Next steps$(printf '\033[0m')

  1. Add this exact redirect URI to your Google OAuth client
     (https://console.cloud.google.com/auth/clients) — keep the localhost one:

       https://$APP_DOMAIN/api/connections/google/callback

  2. Open https://$APP_DOMAIN and sign in with Google.

  3. Back up the encryption key, separately from the database:

       grep ENCRYPTION_KEY $ENV_FILE

Useful afterwards:

  docker compose --env-file $ENV_FILE logs -f worker
  docker compose --env-file $ENV_FILE ps
  docker compose --env-file $ENV_FILE exec -T db pg_dump -U app -d marketing | gzip > backup.sql.gz

EOF
